//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneShop.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Id { get; set; }
        public string JobNo { get; set; }
        public string JobDiscription { get; set; }
        public string OtherDiscription { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsDevice { get; set; }
    }
}
