//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneShop.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repare
    {
        public int Id { get; set; }
        public Nullable<int> Developer_Id { get; set; }
        public Nullable<int> Job_Id { get; set; }
        public string Discription { get; set; }
        public Nullable<double> Cost { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual SystemUser SystemUser { get; set; }
    }
}
